pipeline {
    agent {
        docker { image 'python' }
    }

    stages {
        stage('Node Preparation') {
            steps {
                echo 'Node Preparation #1'
                sh 'curl -fsSL https://deb.nodesource.com/setup_16.x | bash -'
                echo 'Node Preparation #2'
                sh 'apt install -y nodejs'
                echo 'Node Preparation #3'
                sh 'apt install -y xvfb ca-certificates net-tools netcat gnupg2 ffmpeg libgtk-3-0 libgdk-pixbuf2.0-0 libx11-xcb1 libxcb-dri3-0 libxss1 libasound2 libxtst6 libnss3 libxss1 libasound2 libatk-bridge2.0-0 libgtk-2.0-0 libgbm1'
                echo 'Node Preparation #4'
            }
        }
        stage('Dependencies Preparation') {
            steps {
                sh 'apt-get update'
                sh 'apt-get install -y xvfb ca-certificates net-tools netcat gnupg ffmpeg libgtk-3-0 libgdk-pixbuf2.0-dev libxcomposite-dev libdbus-glib-1-2 libatk-bridge2.0-0 wget libgbm1 libnss3 libxss1 libasound2'
                sh 'python -m pip install --upgrade pip'
                sh 'pip install build'
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Browser Lib Preparation') {
            steps {
                sh 'rfbrowser init'
            }
        }
        stage('Tests Execution') {
            steps {
                sh 'chmod +x run.sh'
                sh './run.sh'
            }
        }
    }
    post {
        always {
            robot archiveDirName: 'robot-plugin', logFileName: '**/reports/log.html', otherFiles: '**/reports/**/*.png,**/reports/metrics*.html', outputFileName: '**/reports/output.xml', outputPath: '', overwriteXAxisLabel: '', reportFileName: '**/reports/report.html'
        }
    }
    // Para visualizar html dentro do próprio Jenkins, ir em Gerenciar Jenkins --> Console de script e adicionar a linha abaixo
    // System.setProperty("hudson.model.DirectoryBrowserSupport.CSP","sandbox allow-scripts; default-src 'none'; img-src 'self' data: ; style-src 'self' 'unsafe-inline' data: ; script-src 'self' 'unsafe-inline' 'unsafe-eval' ;")
}
