pipeline {
    agent {
        docker {
            image 'python'
        }
    }

    stages {
        stage('Env Preparation') {
            steps {
                sh 'eccho "teste" && pip install -r requirements.txt'
            }
        }
        stage('Tests Execution') {
            steps {
                sh './run.sh'
            }
        }
    }
}
